<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Lofi_Girl_logo_2024-removebg-preview.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
      <PackageReference Include="font-awesome" Version="4.7.0" />
      <PackageReference Include="Font.Awesome" Version="5.15.4" />
      <PackageReference Include="FontAwesome" Version="4.7.0" />
      <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
      <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
      <PackageReference Include="MaterialDesignColors" Version="5.2.2-ci998" />
      <PackageReference Include="MaterialDesignThemes" Version="5.2.2-ci998" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.14.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.6.25358.103" />
      <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3415-prerelease" />
      <PackageReference Include="SQLite" Version="3.13.0" />
      <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="images\Lofi_Girl_logo_2024-removebg-preview.png" />
      <Resource Include="images\Lofi_Girl_logo_2024-removebg-preview.png" />
      <None Remove="images\Ryan-Gosling_0.jpg" />
      <Content Include="Lofi_Girl_logo_2024-removebg-preview.ico" />
      <Resource Include="images\Ryan-Gosling_0.jpg" />
      <None Remove="images\milad-fakurian-_S-zZyQiOr8-unsplash.jpg" />
      <Resource Include="images\milad-fakurian-_S-zZyQiOr8-unsplash.jpg" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="MVVM\View\CardDisplay\CardDisplayResp.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

</Project>
